CREATE TABLE public.users (
    user_id integer NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying,
    is_active boolean DEFAULT true NOT NULL,
    email_verification_code character varying,
    refresh_token character varying,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    is_verified boolean DEFAULT false NOT NULL,
    google_id character varying,
    facebook_id character varying,
    profile_image character varying
);



CREATE TABLE public.vendors (
    vendor_id integer NOT NULL,
    vendor_uuid uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    business_name character varying(255),
    description character varying(500),
    contact_number character varying(15),
    website character varying(255) NOT NULL,
    address character varying(500),
    legal_documents character varying(255),
    call_out_charges character varying(50),
    verification_status character varying(100) DEFAULT 'unverified'::character varying NOT NULL,
    rating numeric(3,1) DEFAULT '0'::numeric NOT NULL,
    review_count integer DEFAULT 0 NOT NULL,
    completed_jobs integer DEFAULT 0 NOT NULL,
    service_radius numeric(5,2),
    location_zipcode character varying,
    city character varying,
    state character varying,
    business_hours json,
    is_physical_service_provider boolean DEFAULT true NOT NULL,
    portfolio json,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    user_id_fk integer,
    is_available boolean DEFAULT true NOT NULL,
    name character varying(255),
    headline character varying(100),
    about character varying(500),
    is_business boolean DEFAULT false NOT NULL,
    work_experience integer,
    address_line_1 character varying(255),
    address_line_2 character varying(255),
    zipcode character varying(20),
    state_or_province character varying(100),
    postal_code character varying(20),
    country character varying(100),
    service_area character varying(255),
    service_area_postal_code character varying(20),
    service_area_lat numeric(10,7),
    service_area_lng numeric(10,7),
    social_links json,
    cover_photo character varying(255),
    profile_background character varying(255),
    business_card character varying(500),
    profile_card_template json,
    workers_count integer DEFAULT 0 NOT NULL
);


CREATE TABLE public.vendor_services (
    vendor_service_id integer NOT NULL,
    name character varying NOT NULL,
    description text,
    service_highlights json,
    price numeric(10,2) NOT NULL,
    currency public.vendor_services_currency_enum NOT NULL,
    vendor_service_icon character varying,
    vendor_service_image character varying,
    is_physical boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    search_vector tsvector,
    subcategory_id_fk integer NOT NULL,
    vendor_id_fk integer NOT NULL
);
